baseurl = "https://horticulture.coop/"
languageCode = "en-us"
title = "Horticulture Cooperative"
theme = "hugo-agency-theme"
#theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Horticulture Cooperative"
	description = "A cooperative for sustainable development"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

  # agency theme
	# Link custom assets relative to /static
  custom_css = ["css/agency/custom.css", "css/fonts/Bebas_Neue.css"]
  custom_js  = []

	# Navigation
	[params.navigation]
		brand = "Horticulture"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# creative theme
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan = "Growing things of beauty"

		# agency theme
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Growing things of beauty"

    # common
		subtitle = "It's nice to meet you"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		# agency theme
		enable = true
		title = "Holistic development"
		subtitle = "Building products that solve real problems"

		# creative theme
		headline = "What makes us special"

        # [[params.services.list]]
				[[params.services.row]]
				# [[params.services.row.list]]
        #     icon = "fa-compass"
        #     title = "Holistic Development"
        #     description = "Successful products are the right solution for a real need."

        # [[params.services.list]]
        [[params.services.row.list]]
			icon = "fa-cogs"
			title = "Integrated teams"
			description = "Our development teams integrate multiple disciplines to suit your project."

		# [[params.services.list]]
		[[params.services.row.list]]
            icon = "fa-globe"
            title = "Focus on Sustainability"
            description = "We believe that sustainability leads to success."

        # [[params.services.list]]
        [[params.services.row.list]]
            icon = "fa-heart"
            title = "Built with Care"
            description = "Products built with love by artisans who care"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Want to be a part of this?"

		[params.aside.button]
			text = "Apply now"
			link = "#"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "info@horticulture.coop"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
